### ISSUE TITLE
【周刊】第 80 期：生活就像一个鱼缸

### ISSUE THREAD

**Issue by kkjtmac** [openbiox/weekly#1669]
# 生信爱好者周刊（第 80 期）：

这里记录每周值得分享的生信相关内容，周日发布。

本杂志开源（GitHub: [openbiox/weekly](https://github.com/openbiox/weekly)），欢迎提交 issue，投稿或推荐生信相关内容。

[「生信周刊讨论区」](https://github.com/openbiox/weekly/discussions)

## 封面图
![image](https://github.com/openbiox/weekly/assets/45822462/48f376bc-8d5c-41a7-8248-330d4a779c49)
鱼缸-马岩松

## 本周话题：[生活就像一个鱼缸](https://github.com/ruanyf/weekly/blob/master/docs/issue-233.md)
> 当代人看上去很自由，但是实际上，（大多数人的）自由很有限，生活中到处都是看不见的高墙，财富、职业、家庭、阶层等等限制了你能去的地方，每个人其实都生活在自己的鱼缸里面。
## 生信研究
- https://github.com/openbiox/weekly/issues/1372 1
- https://github.com/openbiox/weekly/issues/1192 2
- https://github.com/openbiox/weekly/issues/1653 3

## 博文资讯
- https://github.com/openbiox/weekly/issues/1184 4
- https://github.com/openbiox/weekly/issues/1611 5
- https://github.com/openbiox/weekly/issues/1344 6
- https://github.com/openbiox/weekly/issues/1638 7

## 工具
- https://github.com/openbiox/weekly/issues/930 8
- https://github.com/openbiox/weekly/issues/1269 9
- https://github.com/openbiox/weekly/issues/1276 10
- https://github.com/openbiox/weekly/issues/1652 11

## 资源
- https://github.com/openbiox/weekly/issues/1507 12
- https://github.com/openbiox/weekly/issues/1596 13

## 历史上的本周

- 第 40 期：[bTMB指导肿瘤免疫治疗临床研究](https://mp.weixin.qq.com/s/bS1ap7dOY0yjoxDOMVoaLg)

## 贡献者（GitHub ID）

「Openbiox 生信周刊」运维小队：

- `@ShixiangWang`（王诗翔）
- `@kkjtmac`（阚科佳）
- `@NiEntropy`（赵启祥）
- `@He-Kai-fly`（何凯）
- `@JnanZhang`（张佳楠）
- `@Tomcxf`（陈啸枫）
- `@wangdepin`（王德品）
- `@kongjianyang`（空间阳）

## 订阅

这个周刊每周日发布，同步更新在微信公众号「优雅R」（elegant-r）上。

微信搜索“优雅R”或者扫描二维码，即可订阅。

![](https://cdn.nlark.com/yuque/0/2022/png/471931/1648306398708-897e7ad4-6008-40f8-9200-ddee834b09a7.png)

（完）

**Comment by kkjtmac** [comment]
3、5

**Comment by ShixiangWang** [comment]
> > 3、5
> 
> 4、9

6、8、10

**Comment by Tomcxf** [comment]
> >  > 3、5
> 
> > 4、9

> 6、8、10

1、2、7

**Comment by ShixiangWang** [comment]
6、`[前瞻性研究VS回顾性研究，分清了吗？](https://mp.weixin.qq.com/s/EQZJqW2KJ1VzOdFN3e_RNA)`

![image](https://github.com/openbiox/weekly/assets/25057508/c380d656-d4c9-4313-b6a9-ca724685d272)

前瞻性研究和回顾性研究是流行病学中两种主要的观察性研究方法。本文介绍它们的含义和区别。

8、`[buildr ｜ 舒适地组织和运行构建脚本](https://github.com/netique/buildr)`

![image](https://github.com/openbiox/weekly/assets/25057508/4f79ba76-c52c-4d86-a3d4-a48af05e1fb1)

处理可重复的报告或任何其他类似的项目通常需要运行脚本，以指定的方式“构建”输出文件。`{buildr}`可以帮助你组织、修改和舒适地运行这些脚本。该软件包提供了一组功能，以交互方式指导你完成整个过程，这些功能可以作为RStudio插件使用，这意味着你可以设置键盘快捷键，使你可以随时随地一键选择并运行所需的构建脚本。


10、`[Zotero Better Notes](https://github.com/windingwind/zotero-better-notes)`

![image](https://github.com/openbiox/weekly/assets/25057508/ce6ee8d1-4f79-4253-a49d-f500959ccc6e)

Zotero Better Notes 提供了在 Zotero 中管理笔记的强大工具。

**Comment by Tomcxf** [comment]
1.[【推荐】生信研究 | Nature发表最新人类细胞类型DNA甲基化图谱，发现不同个体相同细胞类型的甲基化模式极其相似 ](https://mp.weixin.qq.com/s/9A7lPjC93MTl1GbuPds-kQ)
DNA甲基化是一种重要的表观遗传标记，但现有的人类DNA甲基化数据集存在很大的局限性。大多数DNA甲基化分析主要针对大块组织，因此掩盖了那些罕见细胞类型。作为部分解决方案，近期有研究利用来自全组织的单细胞转录组测序数据来识别在特定细胞类型中表达的标记基因，然后鉴定出甲基化与表达负相关的特定CpGs，但这对于鉴定液体活检中的罕见细胞可能仍不够准确。
近日，为了克服这些限制并准确表征人类细胞甲基化特征，来自以色列希伯来耶路撒冷大学等单位的研究团队在Nature发表了题为“A DNA methylation atlas of normal human cell types”的文章。研究团队构建了39种不同细胞类型的深度甲基化图谱，并将整个基因组的甲基化模式合并为甲基化的CpG位点模块，使用这些模块来研究不同细胞类型甲基化模式的变化。同时，研究团队还识别描述了组织或细胞类型特异性的甲基化基因组区域，分析了其可能的生物学功能。该甲基化图谱为研究基因调控、疾病相关遗传因素以及开发用于液体活检的组织特异性生物标志物提供了宝贵的数据资源。
![image](https://github.com/openbiox/weekly/assets/75790226/ed90e655-7dd8-4f76-bd54-50b82c48c901)

2.[【推荐】生信研究 | Genome Biology | 稳健、快速、低成本！INSERT-seq方法可对DNA整合特征进行高分辨率定位 ](https://mp.weixin.qq.com/s/K5isCf1mSJqdDGY-BPmaBg)
近日，西班牙巴塞罗那庞培法布拉大学的科研人员在Genome Biology上发表了题为“INSERT-seq enables high-resolution mapping of genomically integrated DNA using Nanopore sequencing”的文章。研究团队开发了一种名为“INSERT-seq”的测序方法，其主要工作流程包括single-tail adapter/tag（STAT-PCR）文库制备和牛津纳米孔（Oxford Nanopore）长读长测序。INSERT-seq方法将整合DNA的靶向扩增、基于唯一分子标记（UMI）的PCR偏差校正以及Oxford Nanopore长读长测序相结合，可以稳健、快速和低成本的方式解析已编辑的基因组中未知的有效载体整合位点，定量分析不同体外、体内样本的DNA整合特征，检测极限为1%。
![image](https://github.com/openbiox/weekly/assets/75790226/a11fdf0c-b72a-4f21-be15-88ae9b397905)

7.[【推荐】博文资讯 | 一文掌握卡方检验](https://mp.weixin.qq.com/s/MGGcHM6t1S6DHQiecpIccA)
本文从假设检验入手，详细介绍了卡方检验的基本内容。
![image](https://github.com/openbiox/weekly/assets/75790226/fe7fc397-0eb2-4ace-b333-61fe20e38437)

**Comment by kkjtmac** [comment]
Thanks all!
