### ISSUE TITLE
Add issue link to the releases?

### ISSUE THREAD

**Issue by pwwang** [openbiox/weekly#2137]
![image](https://github.com/openbiox/weekly/assets/1188067/febb5f4a-bb5f-455f-b602-d309b8e94a70)

Linking the highlighted text to https://openbiox.github.io/weekly/issue-108/ would make lives easier for those watching this repo.

It would be great to add the link in all future releases.

**Comment by ShixiangWang** [comment]
@pwwang Thank you for this good suggestion. 👍
