### ISSUE TITLE
【周刊】第 122 期：他山之石——开启个性化医疗的基因组探索

### ISSUE THREAD

**Issue by ShixiangWang** [openbiox/weekly#2292]
# 生信爱好者周刊（第 122 期）：他山之石——开启个性化医疗的基因组探索

这里记录每周值得分享的生信相关内容，周日发布。

本杂志开源（GitHub: [openbiox/weekly](https://github.com/openbiox/weekly)），欢迎提交 issue，投稿或推荐生信相关内容。

[「生信周刊讨论区」](https://github.com/openbiox/weekly/discussions)

## 封面图

![](https://github.com/openbiox/weekly/assets/25057508/4e1e2634-f4b0-43a9-b9ea-5939965fd09c)

[via](https://www.personalgenomes.org.uk/)

## 本周话题：他山之石——开启个性化医疗的基因组探索

- https://github.com/openbiox/weekly/issues/1717

![image](https://github.com/openbiox/weekly/assets/25057508/8398a89e-d2bd-4b95-b22d-fdc1dbd76e27)

Genomics England是一家领先的基因组研究组织，致力于在英国推动个性化医疗的发展，Genomics England的使命是通过对参与者的基因组进行广泛测序和分析，为研究人员、临床医生和患者提供有关基因与健康之间关系的宝贵信息。2012年时任英国首相卡梅伦在伦敦奥运会上宣布“100,000基因组计划”启动，2013年7月5日Genomics England正式成立，该组织通过实施“100,000基因组计划”，计划测序和研究英国境内10万名患者的基因组数据，2018年12月就已达到了这一目标。通过推动基因组研究和应用，Genomics England成为了个性化医疗的先驱者，为医学科学和患者健康带来了革命性的变革，他们的工作不仅在英国范围内产生了深远影响，还为全球医学界提供了宝贵的经验和启示。

## 生信研究

- https://github.com/openbiox/weekly/issues/1696 1
- https://github.com/openbiox/weekly/issues/1725 2
- https://github.com/openbiox/weekly/issues/1734 3
- https://github.com/openbiox/weekly/issues/1724 4

## 博文资讯

- https://github.com/openbiox/weekly/issues/2284 5
- https://github.com/openbiox/weekly/issues/1517 6
- https://github.com/openbiox/weekly/issues/1658 7
- https://github.com/openbiox/weekly/issues/1491 8
- https://github.com/openbiox/weekly/issues/1478 9
- https://github.com/openbiox/weekly/issues/1565 10

## 工具

- https://github.com/openbiox/weekly/issues/1604 11 
- https://github.com/openbiox/weekly/issues/1752 12
- https://github.com/openbiox/weekly/issues/1735 13
- https://github.com/openbiox/weekly/issues/1711 14

## 资源

- https://github.com/openbiox/weekly/issues/1679 15
- https://github.com/openbiox/weekly/issues/2291 16
- https://github.com/openbiox/weekly/issues/1707 17

## 贡献者（GitHub ID）

「Openbiox 生信周刊」运维小队：

- `@ShixiangWang`（王诗翔）
- `@kkjtmac`（阚科佳）
- `@NiEntropy`（赵启祥）
- `@He-Kai-fly`（何凯）
- `@JnanZhang`（张佳楠）
- `@Tomcxf`（陈啸枫）
- `@wangdepin`（王德品）
- `@kongjianyang`（空间阳）
- `@donghongyu2020`（董弘禹）
- `@DrRobinLuo`（罗鹏）

## 订阅

这个周刊每周日发布，同步更新在微信公众号「优雅R」（elegant-r）上。

微信搜索“优雅R”或者扫描二维码，即可订阅。

![](https://cdn.nlark.com/yuque/0/2022/png/471931/1648306398708-897e7ad4-6008-40f8-9200-ddee834b09a7.png)

（完）

**Comment by ShixiangWang** [comment]
8、10、12

**Comment by Tomcxf** [comment]
> 8、10、12

3、6、7

**Comment by DrRobinLuo** [comment]
> > 8、10、12
> 
> 3、6、7
1、2、16

**Comment by DrRobinLuo** [comment]
> > 8、10、12
> 
> 3、6、7

1、2、16

**Comment by Tomcxf** [comment]
3. [生信研究 | Genome Biology | 王岱峰团队发表跨模态最优传输方法CMOT，可准确预测单细胞的多模态特征](https://mp.weixin.qq.com/s/qYbFAWQg3GN9IdXYSCUBeQ)
2023年7月11日，美国威斯康星大学麦迪逊分校的王岱峰团队在Genome Biology上发表了题为“CMOT: Cross Modality Optimal Transport for multimodal inference”的研究文章。团队提出了跨模态最优传输（CMOT）方法，这是一种基于最优传输（OT）来推断单细胞缺失模式的计算方法，它将可用的多模态数据（源数据）中的细胞比对到一个共同的潜在空间，并推断另一模态（目标数据）中细胞的缺失模态，此推断并不需要成对的源数据多模态数据来进行比对。研究发现，在脑发育、癌症及免疫学等各种应用中，CMOT比现有方法更优秀，并提供改进细胞分类或癌症分类的生物学解释。
![image](https://github.com/openbiox/weekly/assets/75790226/13eef53f-89dc-421c-848e-7b0076df6eb5)
CMOT开源网站：
https://github.com/daifengwanglab/CMOT
原文链接：
https://genomebiology.biomedcentral.com/articles/10.1186/s13059-023-02989-8

6. [博文资讯 | Cancer Cell | 肿瘤突变负荷检测亦有不同：算法过滤种系差异的临床有效性探讨](https://mp.weixin.qq.com/s/oFes0NmBKSjnAL1wvgcz3A?poc_token=HLt9PGaj4iqTmaaDvjyWdTTZsQdbjj9VL7dSktmK)
在Cancer Cell 2022年10月的一期中，Nassar等人从血统差异的视角研究了肿瘤突变负荷与接受免疫检查点抑制剂治疗的患者的预后之间的关系。他们使用名为Oncopanel的下一代测序（NGS）技术研究患者的遗传血统，发现肺癌患者基于TMB的临床结果存在差异，并将其归因于“TMB膨胀 (TMB inflation) ”和需要“重新审视纯粹肿瘤样本的TMB计算”。但是他们也承认他们分析的结果“可能受到小样本大小的限制”。
2023年4月13日，来自剑桥大学的研究人员在Cancer Cell上发表了题目为Not all TMB assays are the same: Clinical validity of robust algorithmic germline filtering的文章，作者提出算法种系过滤可用于准确计算纯肿瘤样本中的TMB-H，而无需进行单独的种系测序。这种方法保持了不同血统的临床有效性，可用于选择肿瘤变异进行个性化ctDNA监测和分子残留疾病检测。作者还强调了在不同基因组分析的复杂生物标志物计算中保持一致性的重要性。
![image](https://github.com/openbiox/weekly/assets/75790226/c5ff2063-a4d4-4ff8-999b-6c53da1ac58b)

原文链接：https://www.cell.com/cancer-cell/fulltext/S1535-6108(23)00090-9?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS1535610823000909%3Fshowall%3Dtrue

7.[博文资讯 | UML活动图大白话入门教程](https://mp.weixin.qq.com/s/NJ391VbEPIrRZCJnOYrtFQ)
本文介绍了UML活动图的基本概念和不同应用场景下的示例，并推荐了PDDON这个在线画图工具。
![image](https://github.com/openbiox/weekly/assets/75790226/005b66f6-a536-45d1-ac20-ebd24d4e6ef9)

**Comment by DrRobinLuo** [comment]
1. [Science｜首个果蝇全生命周期单细胞图谱，揭示衰老相关机制与特征](https://mp.weixin.qq.com/s/mu8STUgFHZLyN7m2kJTTgQ)
2023年6月16日，美国斯坦福大学团队、贝勒医学院团队与Genentech公司的研究团队合作，在Science上发表文章“Aging Fly Cell Atlas identifies exhaustive aging features at cellular resolution”。研究人员使用单细胞RNA测序技术，对果蝇整个生命周期内163种细胞类型的基因表达变化进行了全面分析，建立了迄今为止最完整的果蝇衰老单细胞图谱(Aging Fly Cell Atlas)。该图谱揭示了不同细胞类型在衰老过程中基因表达和组成的动态变化规律，确立了预测生物学年龄的"衰老时钟"模型，为深入理解衰老这一重要生物学过程提供了关键资源。考虑到果蝇与人类在衰老方面的相似性，这一成果有望为延缓衰老、防治老年相关疾病带来新的思路和策略。
![image](https://github.com/openbiox/weekly/assets/42094537/3568110b-7666-4085-9f35-61dd6320539d)
原文链接：https://www.science.org/doi/10.1126/science.adg0934

2. [Nat Genet | 精确度提高6倍！新模型可更精准的预测异常剪接，助力罕见病诊断](https://mp.weixin.qq.com/s/0pz5OTSIK1AY5rRumMZgDg)
这篇发表在Nature Genetics上的研究报告了一种新的机器学习模型AbSplice，可以更精准地预测罕见DNA变异导致的RNA异常剪接。研究人员整合了DNA序列特征和RNA-seq数据，开发了两个版本的AbSplice模型：基于DNA的AbSplice-DNA将预测精确度提高了3倍，而整合RNA数据的AbSplice-RNA则将精确度提高了6倍。这些模型能够通过易获取组织如血液、皮肤的RNA剪接模式，来预测难以取样组织如心脏、大脑中的异常剪接。AbSplice模型有望加速罕见遗传病的分子诊断，为患者提供更精准的遗传学解释。该研究为开发新的基因组学分析工具、挖掘疾病新的遗传机制提供了新思路。
![image](https://github.com/openbiox/weekly/assets/42094537/c2b2fdf6-28e4-462e-ad38-653b02234da9)
原文链接：https://doi.org/10.1038/s41588-023-01373-3

16. [工具/资源推荐 | Globe Explorer：革命性的信息发现之旅](https://mp.weixin.qq.com/s/XMYTnddjwAk9uiPumG0FOw)
Globe Explorer是一个创新的AI驱动的搜索引擎和知识探索平台，为用户提供了一种全新的搜索体验。通过简单输入感兴趣的主题，Globe Explorer就能利用尖端人工智能技术智能分析搜索请求，在网络上探索并呈现最相关的信息来源。与传统的搜索引擎不同，Globe Explorer将搜索结果以类似维基百科的结构化、可视化方式呈现，利用思维导图等方式帮助用户轻松探索知识的广度和深度。它整合了文章、研究报告、视频等多元形式的内容，全方位满足用户的知识需求。同时，Globe Explorer还鼓励用户参与协作式知识构建，用户可以为主题页面贡献自己的见解、添加注释和评论，并与社区分享自己的发现，促进集体智慧的生成。通过Globe Explorer，用户可以节省大量筛选信息的时间，快速高效地连接到可靠且相关的知识来源。总之，Globe Explorer开创性地融合了传统搜索引擎、维基百科和Perplexity AI等工具的优势，代表了知识搜索和探索领域的一大进步。
![image](https://github.com/openbiox/weekly/assets/42094537/2923faaf-5f78-40c6-9c94-7907b9499a63)
网址：https://explorer.globe.engineer/

**Comment by ShixiangWang** [comment]
done, thanks all @openbiox/weekly
