### ISSUE TITLE
【周刊】第 152期

### ISSUE THREAD

**Issue by zoe3251** [openbiox/weekly#2647]
# 生信爱好者周刊（第152期）：

这里记录每周值得分享的生信相关内容，周日发布。

本杂志开源（GitHub: [openbiox/weekly](https://github.com/openbiox/weekly)），欢迎提交 issue，投稿或推荐生信相关内容。

[「生信周刊讨论区」](https://github.com/openbiox/weekly/discussions)

## 封面图
![image](https://github.com/user-attachments/assets/29238d0e-45ad-4b58-8fab-5f90070204bf)

## 本周话题：
- https://github.com/openbiox/weekly/issues/2645
## 生信研究
- https://github.com/openbiox/weekly/issues/2270 1
- https://github.com/openbiox/weekly/issues/2280 2
- https://github.com/openbiox/weekly/issues/2288 3
- https://github.com/openbiox/weekly/issues/2633 4
## 博文资讯
- https://github.com/openbiox/weekly/issues/2055 5
- https://github.com/openbiox/weekly/issues/2072 6
- https://github.com/openbiox/weekly/issues/2241 7
## 工具
- https://github.com/openbiox/weekly/issues/2032 8
- https://github.com/openbiox/weekly/issues/2096 9
- https://github.com/openbiox/weekly/issues/2111 10
## 资源
- https://github.com/openbiox/weekly/issues/2613 11
## 贡献者（GitHub ID）

「Openbiox 生信周刊」运维小队：

- `@ShixiangWang`（王诗翔）
- `@kkjtmac`（阚科佳）
- `@NiEntropy`（赵启祥）
- `@He-Kai-fly`（何凯）
- `@JnanZhang`（张佳楠）
- `@Tomcxf`（陈啸枫）
- `@wangdepin`（王德品）
- `@kongjianyang`（空间阳）
- `@donghongyu2020`（董弘禹）
- `@DrRobinLuo`（罗鹏）
- `@Wangcy-rachel` - 王春阳
- `@zoe3251` - 舒晨阳

## 订阅

这个周刊每周日发布，同步更新在微信公众号「优雅R」（elegant-r）上。

微信搜索“优雅R”或者扫描二维码，即可订阅。

![](https://cdn.nlark.com/yuque/0/2022/png/471931/1648306398708-897e7ad4-6008-40f8-9200-ddee834b09a7.png)

（完）

**Comment by Wangcy-rachel** [comment]
2、3、4

**Comment by Wangcy-rachel** [comment]
2、[Science | Telomere Profiling——一种基于纳米孔测序技术的端粒分析新方法](https://mp.weixin.qq.com/s/tZ5jwBYpYbrLP25Us1q1lg)
![image](https://github.com/user-attachments/assets/a162a218-1a16-471f-a5ef-8a21da755a62)

文章介绍了一种基于纳米孔测序技术的端粒分析方法——Telomere Profiling，可以在单核苷酸分辨率下测量细胞中每个端粒的长度。该方法具有低成本、高度准确性及优异的可重复性。
- 文章链接：https://www.science.org/doi/10.1126/science.ado0431

3、[Nature | 多器官多组学多时间点解析耐力运动后的分子变化](https://mp.weixin.qq.com/s/Bs7lW34VfVJ3AVWvImkwkA)
![image](https://github.com/user-attachments/assets/f3aeeab9-273e-4030-9b98-a86ad25399b7)

文章使用雌雄大鼠模型，从多器官、多组学、多时间点解析耐力运动后的分子变化，并总结分析了其关联生物学通路的组织、性别差异。
- 文章链接：https://www.nature.com/articles/s41586-023-06877-w

4、[Science丨解析迄今最完整小鼠基因组图谱](https://mp.weixin.qq.com/s/a5R3a-KbWmAvANKwDZbopg)
![image](https://github.com/user-attachments/assets/aa87ac49-9001-4e4c-981d-176a608e6d53)

文章综合了众多三代基因测序技术，进行了基因测序和组装，获得了长度为2.77 Gbp（表示十亿个碱基对）的完整的高质量小鼠参考基因组序列，填补了约7.7%的基因组空白。
- 文章链接：https://www.science.org/doi/10.1126/science.adq8191

**Comment by ShixiangWang** [comment]
> 2、3、4

8、9、10

**Comment by ShixiangWang** [comment]
8、`[OpenWDL (The Workflow Description Language (WDL))](https://openwdl.org/)`

<img width="1506" alt="image" src="https://github.com/user-attachments/assets/5c2be3eb-5f08-43a0-bdc2-2af7a21baad0" />

工作流描述语言（WDL）是一种开放标准，用于用人类可读和可写的语法描述数据处理工作流。WDL使得定义分析任务、将它们在工作流中连接起来以及并行执行变得简单直接。该语言力求对所有类型的用户都易于访问和理解，包括程序员、分析师和生产系统操作员。该语言允许使用常见的模式，如散列收集和条件执行，以简单的方式表达。WDL旨在具有可移植性，并提供多种实现方式，可在各种环境中运行，包括高性能计算系统和云平台。


9、`[MuSiC | 多样本单细胞去卷积](https://github.com/xuranw/MuSiC)`

![image](https://github.com/user-attachments/assets/f4b8956f-c20c-476c-a391-b95f99863719)

MuSiC的原始版本是一种去卷积方法，该方法利用跨样本scRNA-seq来估计bulk RNA-seq数据中的细胞类型比例。

MuSiC2是一种迭代算法，旨在通过使用scRNA-seq数据作为参考，在大量RNA-seq数据生成自具有多个临床条件（其中至少有一个条件与scRNA-seq参考不同）的样本时，提高细胞类型去卷积。

10、`[Yew | 用于创建可靠和高效的Web应用程序的Rust/Wasm框架](https://github.com/yewstack/yew)`

![image](https://github.com/user-attachments/assets/4db1183a-53f5-4583-ad71-dbf9b98092f7)
